import base64
import io
from typing import TYPE_CHECKING

import numpy as np

if TYPE_CHECKING:
    from .autocreditscoring import AutoCreditScoring


def _fig_to_base64(fig) -> str:
    buf = io.BytesIO()
    fig.savefig(buf, format='png', dpi=120, bbox_inches='tight')
    buf.seek(0)
    encoded = base64.b64encode(buf.read()).decode('utf-8')
    buf.close()
    return encoded


def _compute_ks(y_true, y_score):
    from sklearn.metrics import roc_curve
    fpr, tpr, _ = roc_curve(y_true, y_score)
    return float(np.max(tpr - fpr))


def export_scorecard_html(acs: "AutoCreditScoring", path: str) -> None:
    if not acs.is_fitted:
        raise RuntimeError("AutoCreditScoring instance is not fitted. Call fit() first.")

    auc_train = acs.auc_train
    auc_valid = acs.auc_valid

    y_score_valid = acs.model.predict_proba(acs.valid_woe)[:, 1]
    ks_stat = _compute_ks(acs.valid[acs.target], y_score_valid)

    roc_b64 = _fig_to_base64(acs.plot_roc())
    ks_b64 = _fig_to_base64(acs.plot_ks())
    score_dist_b64 = _fig_to_base64(acs.plot_score_distribution())
    iv_b64 = _fig_to_base64(acs.plot_iv())
    disc_b64 = _fig_to_base64(acs.plot_discretized_features())

    scorecard = acs.credit_scoring.scorecard.reset_index()
    scorecard_html = scorecard.to_html(index=False, classes='scorecard-table', border=0)

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Credit Scorecard Report</title>
<style>
  body {{
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    max-width: 1100px;
    margin: 0 auto;
    padding: 30px 20px;
    background: #f5f7fa;
    color: #333;
  }}
  h1 {{
    color: #2c3e50;
    border-bottom: 3px solid #3498db;
    padding-bottom: 10px;
  }}
  h2 {{
    color: #2c3e50;
    margin-top: 40px;
    border-bottom: 2px solid #bdc3c7;
    padding-bottom: 6px;
  }}
  .metrics {{
    display: flex;
    gap: 20px;
    flex-wrap: wrap;
    margin: 20px 0;
  }}
  .metric-card {{
    background: #fff;
    border-radius: 8px;
    padding: 16px 24px;
    box-shadow: 0 2px 8px rgba(0,0,0,0.08);
    min-width: 140px;
    text-align: center;
  }}
  .metric-card .label {{
    font-size: 13px;
    color: #7f8c8d;
    text-transform: uppercase;
    letter-spacing: 0.5px;
  }}
  .metric-card .value {{
    font-size: 28px;
    font-weight: 700;
    color: #2c3e50;
    margin-top: 4px;
  }}
  .scorecard-table {{
    width: 100%;
    border-collapse: collapse;
    background: #fff;
    border-radius: 8px;
    overflow: hidden;
    box-shadow: 0 2px 8px rgba(0,0,0,0.08);
    font-size: 14px;
  }}
  .scorecard-table thead th {{
    background: #3498db;
    color: #fff;
    padding: 10px 14px;
    text-align: left;
    font-weight: 600;
  }}
  .scorecard-table tbody td {{
    padding: 8px 14px;
    border-bottom: 1px solid #ecf0f1;
  }}
  .scorecard-table tbody tr:nth-child(even) {{
    background: #f8f9fa;
  }}
  .plot-container {{
    background: #fff;
    border-radius: 8px;
    padding: 16px;
    margin: 20px 0;
    box-shadow: 0 2px 8px rgba(0,0,0,0.08);
    text-align: center;
  }}
  .plot-container img {{
    max-width: 100%;
    height: auto;
  }}
  footer {{
    text-align: center;
    margin-top: 50px;
    padding: 20px 0;
    color: #95a5a6;
    font-size: 12px;
    border-top: 1px solid #ecf0f1;
  }}
</style>
</head>
<body>

<h1>Credit Scorecard Report</h1>

<h2>Summary Metrics</h2>
<div class="metrics">
  <div class="metric-card">
    <div class="label">AUC Train</div>
    <div class="value">{auc_train:.4f}</div>
  </div>
  <div class="metric-card">
    <div class="label">AUC Validation</div>
    <div class="value">{auc_valid:.4f}</div>
  </div>
  <div class="metric-card">
    <div class="label">KS Statistic</div>
    <div class="value">{ks_stat:.4f}</div>
  </div>
</div>

<h2>Scorecard</h2>
{scorecard_html}

<h2>ROC Curve</h2>
<div class="plot-container">
  <img src="data:image/png;base64,{roc_b64}" alt="ROC Curve">
</div>

<h2>KS Chart</h2>
<div class="plot-container">
  <img src="data:image/png;base64,{ks_b64}" alt="KS Chart">
</div>

<h2>Score Distribution</h2>
<div class="plot-container">
  <img src="data:image/png;base64,{score_dist_b64}" alt="Score Distribution">
</div>

<h2>Information Value</h2>
<div class="plot-container">
  <img src="data:image/png;base64,{iv_b64}" alt="IV Report">
</div>

<h2>Discretized Features</h2>
<div class="plot-container">
  <img src="data:image/png;base64,{disc_b64}" alt="Discretized Features">
</div>

<footer>
  Generated by WOE Credit Scoring Toolkit v3.0
</footer>

</body>
</html>"""

    with open(path, 'w', encoding='utf-8') as f:
        f.write(html)
